---
micronaut:
#  io:
#    watch:
#      paths: src/main
#      restart: true
  application:
    name: micronautdemo2
    helloworld:
      name: pietje

appproperties:
    name: keesje
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''    
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

endpoints:
  info:
    enabled: true
    sensitive: false
  health:
    details-visible: ANONYMOUS
  routes:
    enabled: true
    sensitive: false
